[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://hkdyuasngmyzrhydariq.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZHl1YXNuZ215enJoeWRhcmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNjk5OTQsImV4cCI6MjEwNDk0NTk5NH0.quOfiPh96n8nNT7bnO32tQZtZvMQZGvRuKDIOpn7nNU"

